version: "3.4"
services:
  creditcard:
     image: societyhack/creditcard-api:latest
     ports:
       - 8084:80
     deploy:
       endpoint_mode: vip
       update_config:
         parallelism: 1
         delay: 10s
       restart_policy:
           condition: on-failure
       replicas: 2
       placement:
         constraints:
           - node.labels.role==microservices
     #healthcheck:
      # test: [“CMD”, “curl”, “-f”, “http://localhost:80/docs/“]
      #interval: 1m30s
      # timeout: 10s
      # retries: 3
      # start_period: 40s  

